/* =====================================================
   Project: Movie Popularity & Trends
   Database: DVD Rental (PostgreSQL)
   ===================================================== */


/* ========== Section A: Basic Queries (1–10) ========== */

-- Q1: List all films with their titles and release years
SELECT title, release_year
FROM film;

-- Q2: Find the total number of films in the database
SELECT COUNT(*) AS total_films
FROM film;

-- Q3: Show the names of all customers who rented at least one film
SELECT DISTINCT c.first_name, c.last_name
FROM customer c
JOIN rental r ON c.customer_id = r.customer_id;

-- Q4: Retrieve the titles of films in the "Action" category
SELECT f.title
FROM film f
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
WHERE c.name = 'Action';

-- Q5: Count how many films belong to each category
SELECT c.name AS category_name, COUNT(fc.film_id) AS film_count
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
GROUP BY c.name;

-- Q6: Display the top 5 longest films by length
SELECT title, length
FROM film
ORDER BY length DESC
LIMIT 5;

-- Q7: Find the number of rentals made in January 2006
SELECT COUNT(*) AS total_rentals
FROM rental
WHERE rental_date >= '2006-01-01'
  AND rental_date < '2006-02-01';

-- Q8: Show all films that have rental rates greater than $3
SELECT title, rental_rate
FROM film
WHERE rental_rate > 3;

-- Q9: List all distinct cities where customers live
SELECT DISTINCT ci.city
FROM customer c
JOIN address a ON c.address_id = a.address_id
JOIN city ci ON a.city_id = ci.city_id;

-- Q10: Find the staff members who processed rentals
SELECT DISTINCT s.first_name, s.last_name
FROM staff s
JOIN rental r ON s.staff_id = r.staff_id;


/* ========== Section B: Intermediate Queries (11–20) ========== */

-- Q11: Find the top 10 films by number of rentals
SELECT f.title, COUNT(r.rental_id) AS rental_count
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

-- Q12: Show the revenue generated by each film
SELECT f.title, SUM(p.amount) AS total_revenue
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
JOIN payment p ON r.rental_id = p.rental_id
GROUP BY f.title
ORDER BY total_revenue DESC;

-- Q13: List customers who rented more than 20 films
SELECT c.first_name, c.last_name, COUNT(r.rental_id) AS rental_count
FROM customer c
JOIN rental r ON c.customer_id = r.customer_id
GROUP BY c.customer_id
HAVING COUNT(r.rental_id) > 20;

-- Q14: Find the average rental duration for each category
SELECT c.name AS category_name, AVG(f.rental_duration) AS avg_duration
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name;

-- Q15: Display films that were rented but never returned late
SELECT DISTINCT f.title
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
WHERE r.return_date <= r.rental_date + INTERVAL '1 day' * f.rental_duration;

-- Q16: Identify the most popular film category by rental count
SELECT c.name, COUNT(r.rental_id) AS rental_count
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN inventory i ON fc.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY c.name
ORDER BY rental_count DESC
LIMIT 1;

-- Q17: Show the monthly rental count trend for 2005–2006
SELECT DATE_TRUNC('month', rental_date) AS month, COUNT(*) AS rental_count
FROM rental
WHERE rental_date BETWEEN '2005-01-01' AND '2006-12-31'
GROUP BY month
ORDER BY month;

-- Q18: Find customers who rented films from more than 5 categories
SELECT c.first_name, c.last_name, COUNT(DISTINCT cat.category_id) AS category_count
FROM customer c
JOIN rental r ON c.customer_id = r.customer_id
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film_category fc ON i.film_id = fc.film_id
JOIN category cat ON fc.category_id = cat.category_id
GROUP BY c.customer_id
HAVING COUNT(DISTINCT cat.category_id) > 5;

-- Q19: List films that were rented by customers from Canada
SELECT DISTINCT f.title
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
JOIN customer c ON r.customer_id = c.customer_id
JOIN address a ON c.address_id = a.address_id
JOIN city ci ON a.city_id = ci.city_id
JOIN country co ON ci.country_id = co.country_id
WHERE co.country = 'Canada';

-- Q20: Show the top 5 customers by total payment amount
SELECT c.first_name, c.last_name, SUM(p.amount) AS total_spent
FROM customer c
JOIN payment p ON c.customer_id = p.customer_id
GROUP BY c.customer_id
ORDER BY total_spent DESC
LIMIT 5;


/* ========== Section C: Advanced Queries (21–30) ========== */

-- Q21: Rank films by rental frequency using a window function
SELECT f.title,
       COUNT(r.rental_id) AS rental_count,
       RANK() OVER (ORDER BY COUNT(r.rental_id) DESC) AS rank
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title;

-- Q22: Use a CTE to calculate monthly revenue and display top 3 months
WITH monthly_revenue AS (
    SELECT DATE_TRUNC('month', payment_date) AS month,
           SUM(amount) AS revenue
    FROM payment
    GROUP BY month
)
SELECT *
FROM monthly_revenue
ORDER BY revenue DESC
LIMIT 3;

-- Q23: Find films that generated revenue above the overall average
SELECT f.title, SUM(p.amount) AS total_revenue
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
JOIN payment p ON r.rental_id = p.rental_id
GROUP BY f.title
HAVING SUM(p.amount) >
(
    SELECT AVG(total_rev)
    FROM (
        SELECT SUM(p2.amount) AS total_rev
        FROM inventory i2
        JOIN rental r2 ON i2.inventory_id = r2.inventory_id
        JOIN payment p2 ON r2.rental_id = p2.rental_id
        GROUP BY i2.film_id
    ) sub
);

-- Q24: Calculate customer lifetime value
SELECT c.first_name, c.last_name, SUM(p.amount) AS lifetime_value
FROM customer c
JOIN payment p ON c.customer_id = p.customer_id
GROUP BY c.customer_id
ORDER BY lifetime_value DESC;

-- Q25: Identify films that were rented in consecutive months
SELECT DISTINCT f.title
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r1 ON i.inventory_id = r1.inventory_id
JOIN rental r2 ON i.inventory_id = r2.inventory_id
WHERE DATE_TRUNC('month', r2.rental_date) =
      DATE_TRUNC('month', r1.rental_date) + INTERVAL '1 month';

-- Q26: Create a materialized view showing film popularity by category
DROP MATERIALIZED VIEW IF EXISTS film_popularity_by_category;

CREATE MATERIALIZED VIEW film_popularity_by_category AS
SELECT c.name AS category_name,
       f.title,
       COUNT(r.rental_id) AS rental_count
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY c.name, f.title;


-- Q27: Stored function to calculate revenue for a given film ID
DROP FUNCTION IF EXISTS film_revenue(INT);

CREATE OR REPLACE FUNCTION film_revenue(f_id INT)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $$
DECLARE total NUMERIC;
BEGIN
    SELECT SUM(p.amount)
    INTO total
    FROM inventory i
    JOIN rental r ON i.inventory_id = r.inventory_id
    JOIN payment p ON r.rental_id = p.rental_id
    WHERE i.film_id = f_id;

    RETURN total;
END;
$$;
-- Example:
-- SELECT film_revenue(1);

-- Q28: Trigger to log whenever a rental is returned late

DROP TRIGGER IF EXISTS late_return_trigger ON rental;
DROP FUNCTION IF EXISTS log_late_return();

CREATE OR REPLACE FUNCTION log_late_return()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE allowed_days INT;
BEGIN
    SELECT f.rental_duration
    INTO allowed_days
    FROM inventory i
    JOIN film f ON i.film_id = f.film_id
    WHERE i.inventory_id = OLD.inventory_id;

    IF NEW.return_date IS NOT NULL
       AND NEW.return_date > OLD.rental_date + (allowed_days || ' days')::INTERVAL
    THEN
        INSERT INTO late_returns_log (rental_id, return_date)
        VALUES (NEW.rental_id, NEW.return_date);
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER late_return_trigger
AFTER UPDATE OF return_date ON rental
FOR EACH ROW
EXECUTE FUNCTION log_late_return();
-- Q29: Calculate yearly revenue
SELECT EXTRACT(YEAR FROM payment_date) AS year,
       SUM(amount) AS yearly_revenue
FROM payment
GROUP BY year
ORDER BY year;

-- Q30: Optimize a query using index for film search by title
CREATE INDEX idx_film_title ON film(title);

-- Example optimized query:
-- SELECT * FROM film WHERE title = 'ACADEMY DINOSAUR';


