SELECT * FROM zepto_v2;
SELECT name, mrp FROM zepto_v2;
SELECT DISTINCT ï»¿Category FROM zepto_v2;
SELECT * FROM zepto_v2 WHERE mrp > 3000;
SELECT * FROM zepto_v2 WHERE discountPercent > 15;
SELECT * FROM zepto_v2 WHERE outOfStock = FALSE;
SELECT * FROM zepto_v2 WHERE weightInGms > 500;
SELECT * FROM zepto_v2 WHERE availableQuantity<5;
SELECT distinct ï»¿Category FROM zepto_v2;
SELECT count(name) FROM zepto_v2;
SELECT * FROM zepto_v2 ORDER BY mrp ASC;
SELECT * FROM zepto_v2 ORDER BY discountPercent DESC;
SELECT * FROM zepto_v2 ORDER BY mrp DESC LIMIT 10;
SELECT * FROM zepto_v2 WHERE name="T%";
SELECT count(outOfStock) FROM zepto_v2;
SELECT * FROM zepto_v2 WHERE quantity>50;
SELECT * FROM zepto_v2 WHERE mrp BETWEEN 2000 AND 4000;
SELECT * FROM zepto_v2 WHERE discountedSellingPrice<1500;
SELECT * FROM zepto_v2 WHERE weightInGms=1000;
SELECT * FROM zepto_v2 WHERE ï»¿Category LIKE "%Vegetables%";
SELECT ï»¿Category, max(mrp) FROM zepto_v2 GROUP BY ï»¿Category;
SELECT ï»¿Category, min(discountedSellingPrice) FROM zepto_v2 GROUP BY ï»¿Category ;
SELECT ï»¿Category, count(name) AS no_products_in_each_category FROM zepto_v2 GROUP BY ï»¿Category;
SELECT name,avg(mrp) FROM zepto_v2 GROUP BY name;
SELECT ï»¿Category ,sum(availableQuantity) FROM zepto_v2 GROUP BY ï»¿Category;
SELECT * FROM zepto_v2 WHERE mrp and discountedSellingPrice>1000;
SELECT name,avg(discountPercent) as ADP FROM zepto_v2 WHERE "discountPercent">"ADP" GROUP BY name;
SELECT ï»¿Category,count(name) as PRODUCTS FROM zepto_v2 GROUP BY ï»¿Category HAVING PRODUCTS >50;
SELECT name, discountPercent FROM zepto_v2 ORDER BY discountPercent DESC LIMIT 5;
SELECT name,weightInGms * availableQuantity as AVL_QUANT FROM zepto_v2 ;
SELECT name,mrp,discountPercent,discountedSellingPrice FROM zepto_v2 WHERE discountPercent >=50;
SELECT * FROM zepto_v2 WHERE name LIKE "%coconut%";
SELECT name, sum(discountedSellingPrice * availableQuantity) as total_value FROM zepto_v2 GROUP BY name;
SELECT ï»¿Category, avg(discountPercent) as HIGHEST_AVG_DISCOUNT FROM zepto_v2 GROUP BY ï»¿Category ORDER BY HIGHEST_AVG_DISCOUNT DESC LIMIT 1;
SELECT * FROM zepto_v2 WHERE availableQuantity=0 AND outOfStock =FALSE;
SELECT *, RANK() OVER(PARTITION BY "ï»¿Category" ORDER BY mrp DESC) as mrp_rank FROM zepto_v2;
SELECT * FROM (SELECT *, DENSE_RANK() OVER(PARTITION BY "ï»¿Category" ORDER BY mrp DESC) as rnk FROM zepto_v2) WHERE rnk = 2;
SELECT "ï»¿Category", name, availableQuantity, SUM(availableQuantity) OVER(PARTITION BY "ï»¿Category" ORDER BY name) as cumulative_qty FROM zepto_v2;
SELECT * FROM (SELECT *, AVG(mrp) OVER(PARTITION BY "ï»¿Category") as avg_cat_mrp FROM zepto_v2) WHERE mrp > avg_cat_mrp;
SELECT * FROM (SELECT *, AVG(discountPercent) OVER(PARTITION BY "ï»¿Category") as avg_cat_discount FROM zepto_v2) WHERE discountPercent > avg_cat_discount;
CREATE VIEW HighDiscountInStock AS SELECT * FROM zepto_v2 WHERE outOfStock = 'FALSE' AND discountPercent > 20;
UPDATE zepto_v2 SET outOfStock = 'TRUE' WHERE availableQuantity = 0;
DELIMITER // CREATE PROCEDURE GetProductsByCategory (IN catName VARCHAR(255)) BEGIN SELECT * FROM zepto_v2 WHERE "ï»¿Category" = catName; END // DELIMITER ;
DELIMITER // CREATE FUNCTION GetDiscountAmt (m_price DECIMAL(10,2), s_price DECIMAL(10,2)) RETURNS DECIMAL(10,2) DETERMINISTIC BEGIN RETURN (m_price - s_price); END // DELIMITER ;
SELECT name, COUNT(*) FROM zepto_v2 GROUP BY name HAVING COUNT(*) > 1;
SELECT * FROM (SELECT *, ROW_NUMBER() OVER(PARTITION BY "ï»¿Category" ORDER BY mrp ASC) as cheap_rank FROM zepto_v2) WHERE cheap_rank <= 3;
SELECT "ï»¿Category", SUM(mrp * availableQuantity) as stock_value FROM zepto_v2 GROUP BY "ï»¿Category" HAVING stock_value > 100000;
DELIMITER // CREATE TRIGGER auto_out_of_stock BEFORE UPDATE ON zepto_v2 FOR EACH ROW BEGIN IF NEW.availableQuantity = 0 THEN SET NEW.outOfStock = 'TRUE'; END IF; END // DELIMITER ;
SELECT "ï»¿Category", COUNT(*) as total_prod, AVG(mrp) as avg_mrp, AVG(discountPercent) as avg_disc FROM zepto_v2 GROUP BY "ï»¿Category";
SELECT * FROM zepto_v2 WHERE mrp > (SELECT AVG(mrp) FROM zepto_v2);